### PR TITLE
List stucture

### PR DESCRIPTION
**Pull request by AbdimulhinYussuf3675**
In this branch, I set up a new project with webpack that is based on the webpack exercise i have already completed. I was also able to :

- [x] Write a function to iterate over the tasks array and populate an HTML list item element for each task
- [x]  On page load render the dynamically created list of tasks in the dedicated placeholder. The list should appear in order of the index values for each task.
- [x] Create a style.css and set rules for the To-Do List. CSS must be loaded by Webpack Style/CSS Loader.
- [x] All my source files (index.html, index.js, and style.css) must be located in the/src directory and your distribution files will be generated by webpack and served by webpack dev server from the/dist folder

### CODE REVIEW

**Comment by prolajumokeoni** [comment]
Hi @AbdimulhinYussuf3675, Can you update all sections of your readme with your personalized content for your app? this is a requirement to get a review

**Comment by AbdimulhinYussuf3675** [comment]
@prolajumokeoni, Hello I have just updated it you can check it out. Thanks

**Comment by prolajumokeoni** [comment]
Hi @AbdimulhinYussuf3675,  please can you add  the key features section content for your app

**Comment by prolajumokeoni** [comment]
Hi @AbdimulhinYussuf3675 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that  does does not have the key features section in your readme and please update the Mit license link it is broken

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by codecaiine — COMMENTED** [review]
Hi @AbdimulhinYussuf3675 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has microverse logo at the top. Please remove the microverse logo from your readme or replace it with your own logo to make it more professional, and show that the project it is your own :+1: 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me (@codecaiine) in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by tresorsawasawa — APPROVED** [review]
# STATUS: APPROVE :heavy_check_mark: :heavy_check_mark:  :champagne: 

Hi @AbdimulhinYussuf3675 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 :clap: :clap: :100: 

nodding-yes

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
- Your README file is professional :heavy_check_mark: 

## Optional suggestions

- [ **OPTIONAL** ] **IMPORTANT:** To make your README more professional, I suggest you use the working link on your Live Demo section as the current one is broken.

_Every comment with the **[OPTIONAL]** prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
